baseURL = "https://harnois-ezkit.netlify.com/"
DefaultContentLanguage = "en"
title = "EzKit"
theme = "beauharnois"
description = ""

# Pointing to this file
config = "config.toml"
contentdir = "content"
disableKinds = ["taxonomy","taxonomyTerm","RSS"]
# Create an array of files you don't want hugo to build
ignoreFiles = []
# Enable Logging
log = false
preserveTaxonomyNames = true
pygmentsUseClasses = true
relativeURLs = true
languageCode = "en-us"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir = false

#CUSTOM PARAMS
[params]
  ## Include google maps, with API Key
  googleapikey = ""
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://harnois-ezkit.netlify.com/"
  siteaddressno = "https://harnois-ezkit.netlify.com"
  ## FB share info
  fbpagename = ""
  fbappid = ""
  ## Business name in Schema.org
  schemabiz = "EzKit"
  ## Google Tag Manager tracking ID
  gtmid = ""

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[permalinks]
  singles = "/:slug/"

[Languages]
[Languages.en]
[Languages.en.permalinks]
  singles = "/:slug/"

[Languages.fr]
[Languages.fr.permalinks]
  singles = "/:slug/"
